runtime: python39
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app
instance_class: F2
max_instances: 4
env_variables:
  _PROJECT_NAME: ##_PROJECT_NAME##
  _VERSION_NAME: ##_VERSION_NAME##
  _SHORT_SHA: ##_SHORT_SHA##
  _BRANCH_NAME: ##_BRANCH_NAME##
  _REPO_NAME: ##_REPO_NAME##