runtime: python39
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app
instance_class: F2
env_variables:
  PROJECT_NAME: Mobile Doc Backend
  VERSION_NAME: dev
  PROJECT_ID: ${_PROJECT_ID}
  SHORT_SHA: ${_SHORT_SHA}
  BRANCH_NAME: ${_BRANCH_NAME}
  REPO_NAME: ${_REPO_NAME}