steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  env-vars:
   - ATLAS_USERNAME: ${_ATLAS_USERNAME}
  args: 
   - '-c'
   - |
      sed -i "s/##_ATLAS_USERNAME##/$${ATLAS_USERNAME}/g" app.yaml
      gcloud config set app/cloud_build_timeout 1600
      gcloud app deploy --version ${_VERSION}

timeout: '1600s'
substitutions:
  _ATLAS_USERNAME: ${_ATLAS_USERNAME}