steps:
  - name: 'gcr.io/cloud-builders/python:3.8'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        python create_env.py
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'app'
      - 'deploy'
      - 'app.yaml'

timeout: "1600s"
