steps:
# Step 1: Set up environment variables
- name: "ubuntu"
  args: ["bash", "./cloud_env.sh"]  
  env:
    - "_PROJECT_NAME=${PROJECT_NAME}"  

# Step 2: Deploy the app using gcloud app deploy
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
  timeout: "1600s"
