name: Run UnitTest

on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ main, dev ]

jobs:
  unittest:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11.0
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.0

    - name: Create SA Key to be used for GCP Authentication
      run: |
        echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} | base64 --decode > sa_github_key.json

    - name: GCP Auth with Service Account Key JSON
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: mobile-doc-backend

    - name: Install dependencies
      run: |
        echo "upgrading pip"
        python -m pip install --upgrade pip
        echo "Downloading pyconnector"
        echo "Installing the following packages"
        cat requirements.txt
        pip install -r requirements.txt
        echo "Installing httpx, pytest, asyncio anyio"
        pip install httpx==0.23.1 pytest==7.2.0 pytest-asyncio==0.20.2 anyio==3.6.2
    
    - name: Test with pytest
      run: |
        python -m pytest -s -v 
      env:
        _ATLAS_USERNAME: ${{ secrets._ATLAS_USERNAME }}
        _ATLAS_PASSWORD: ${{ secrets._ATLAS_PASSWORD }}
        _REDIS_PASSWORD: ${{ secrets._REDIS_PASSWORD }}